"""wiki table

Revision ID: 164e508903cd
Revises: 37029c0cd21f
Create Date: 2020-04-10 00:09:15.763597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164e508903cd'
down_revision = '37029c0cd21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('children', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wiki')
    # ### end Alembic commands ###
