"""wiki table

Revision ID: 8a627de4819b
Revises: 164e508903cd
Create Date: 2020-04-10 01:01:20.756496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a627de4819b'
down_revision = '164e508903cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('children', sa.JSON(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wiki')
    # ### end Alembic commands ###
